name: Generate changelog
on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(changelog): update release notes"
          COMMITTER: "github-actions[bot] 41898282+github-actions[bot]@users.noreply.github.com"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements"
          DEFAULT_SCOPE: "*"
          REGENERATE_COUNT: 4
